// Copies contract ABIs from Foundry's build output, so neither the app nor the indexer hand-writes
// an ABI. Run after `forge build` in ../contracts: `pnpm abi`.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

mkdirSync("../indexer/abis", { recursive: true });
for (const name of ["CreatorRegistry", "LicenseRegistry", "LicenseEscrow", "ReceiptAnchor"]) {
  const { abi } = JSON.parse(readFileSync(`../contracts/out/${name}.sol/${name}.json`, "utf8"));
  writeFileSync(`lib/abi/${name}.ts`, `// Generated by scripts/abi.mjs from contracts/out. Do not edit.\nexport const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`);
  writeFileSync(`../indexer/abis/${name}.json`, JSON.stringify(abi, null, 2) + "\n");
  console.log(name, abi.length, "entries");
}
