import "server-only";
/**
 * The DevRenderer: no model. Composites the licence's reference images with a large "TEST RENDER"
 * overlay, the prompt and the licence number, so nobody can mistake it for a generated image. It
 * exists so the rest of the pipeline (C2PA, receipt, payout, verifier) runs before model keys arrive.
 */
import sharp from "sharp";
import type { RenderInput, RenderOutput } from "./types";

const W = 1024;
const H = 1024;

const esc = (s: string) => s.replace(/[<>&"']/g, (c) => `&#${c.charCodeAt(0)};`);

function wrap(text: string, width: number, max: number): string[] {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    if ((line + " " + word).trim().length > width) {
      lines.push(line.trim());
      line = word;
      if (lines.length === max) break;
    } else line += " " + word;
  }
  if (lines.length < max && line.trim()) lines.push(line.trim());
  return lines;
}

export async function devRender(input: RenderInput): Promise<RenderOutput> {
  const n = Math.max(1, Math.min(3, input.references.length));
  const tileW = Math.floor(W / n);
  const tiles = await Promise.all(
    input.references.slice(0, n).map(async (ref, i) => ({
      input: await sharp(ref).resize(tileW, 640, { fit: "cover" }).modulate({ saturation: 0.6 }).toBuffer(),
      left: i * tileW,
      top: 160,
    })),
  );
  const prompt = wrap(input.prompt, 58, 4);
  const overlay = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
    <rect width="${W}" height="160" fill="#101012"/>
    <rect y="800" width="${W}" height="224" fill="#101012"/>
    <text x="32" y="62" font-family="Helvetica, Arial" font-size="40" font-weight="700" fill="#f5e663">TEST RENDER</text>
    <text x="32" y="104" font-family="Helvetica, Arial" font-size="22" fill="#c2c2c8">Not generated by a model. Reference composite from the Likeness DevRenderer.</text>
    <text x="32" y="138" font-family="Helvetica, Arial" font-size="22" fill="#8c8c95">Licence #${input.licenceId} · render ${input.renderIndex}</text>
    <g transform="translate(${W / 2} ${160 + 320}) rotate(-28)">
      <text text-anchor="middle" font-family="Helvetica, Arial" font-size="150" font-weight="800" fill="#f5e663" fill-opacity="0.55">TEST RENDER</text>
    </g>
    <text x="32" y="846" font-family="Helvetica, Arial" font-size="20" fill="#8c8c95">PROMPT</text>
    ${prompt.map((l, i) => `<text x="32" y="${884 + i * 32}" font-family="Helvetica, Arial" font-size="26" fill="#f3f3f5">${esc(l)}</text>`).join("")}
  </svg>`;
  const bytes = await sharp({ create: { width: W, height: H, channels: 3, background: "#232328" } })
    .composite([...tiles, { input: Buffer.from(overlay), left: 0, top: 0 }])
    .jpeg({ quality: 88 })
    .toBuffer();
  return { bytes: new Uint8Array(bytes), mime: "image/jpeg", provider: "dev", model: "likeness-dev-renderer (no model)", test: true };
}
